### ISSUE TITLE
can't disconnect a linkedin profile

### ISSUE THREAD

**Issue by buzzworkers** [mapkyca/KnownLinkedin#12]
my post screen is now like this : https://i.imgur.com/EiYrThtl.jpg
and my setting/linkedin : http://i.imgur.com/wFZDpWQ.png

I want to remove the (disconnect) link to linkedin but when i click it button does nothing

is there a way i could clean this remain from my database from command line ?

kylewm recommended this : 

if you can get to the mysql command line, you can do: select uuid,contents from entities where entity_subtype='Idno\\Entities\\User';
and then update entities set contents='{edited contents}' where uuid='the uuid returned by the first query'

but i'im not sure how to translate this into mysql command line. 
i could probabaly install phpmyadmin if it can help find out what this remain connection is.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/KnownLinkedin/issues/12" class="u-in-reply-to"></a>The database contains the object in a json encoded form, so theoretically you could extract it, edit it in a text editor, and then save it back.

This is a little hairy, since a misplaced comma could render the object inaccessible... so be sure to take a backup first!
